#include "glue/registration.h"
#include "stdio.h"

// naming might be constructed as something_fileidfromcmake_linenumber

/* MACRO STARTS HERE */

void s1_f(char *args[], struct ResultReporter *reporter);

struct StepInfo s1_i = {
    .position = "/.../filename.c:42", // __FILE__:__LINE__
    .expressionType = "regex",
    .expression = "I eat (d+) cukes", // macro param
    .body = s1_f
};

void s1_f(char *args[], struct ResultReporter *reporter) /* MACRO ENDS HERE */ {
    printf("C step executed");
//    reporter->failed("thisfile:thisline", "stuff happened!"); // TODO UNCOMMENT THIS
}


/*
 * This can be generated by cmake before compiling, defining our function...
 *
 *   ADD_CUCUMBER_C_STEPS(example2.c)
 *
 * ...that creates a file with the steps variable by parsing source files.
 */

struct StepInfo *steps[] = {
    &s1_i // , ...
};

/*
 * This must be included with all step library.
 * Compiler-dependent (different between MSVC and the others).
 */

//extern struct StepDef *steps[];

__attribute__((constructor)) void begin() {
    for (struct StepInfo **i = steps; *i != 0; ++i)
        registerGlue(*i);
}

__attribute__((destructor)) void end() {
    for (struct StepInfo **i = steps; *i != 0; ++i)
        unregisterGlue(*i);
}

/*
 * The library should register itself to be called by ID.
 */
